/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  safelist: [
    'font-playfair',
    'font-montserrat',
    'font-lato',
    'font-raleway',
    'font-opensans',
    'font-roboto',
    'font-poppins',
    'font-inter',
    'font-nunito',
    'font-merriweather',
    'font-crimson',
    'font-lora',
    'font-source',
    'font-ubuntu',
    'font-dancing',
    'font-pacifico',
    'font-caveat',
    'font-bebas',
    'font-oswald',
    'font-abril',
    'font-bungee',
    'font-righteous',
    'font-barlow',
    'font-worksans',
    'font-spacegrotesk',
    'font-outfit',
    'font-dmsans',
    'font-plusjakarta',
    'font-manrope',
    'font-sora',
    'font-figtree',
    'font-syne',
    'font-spacemono',
    'font-jetbrains',
    'font-comfortaa',
    'font-quicksand',
    'font-rubik',
    'font-kalam',
    'font-satisfy',
    'font-greatvibes',
    'font-amatic',
    'font-shadows',
    'font-permanent',
    'font-indie',
  ],
  theme: {
    extend: {
      fontFamily: {
        playfair: ['Playfair Display', 'serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        opensans: ['Open Sans', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
        merriweather: ['Merriweather', 'serif'],
        crimson: ['Crimson Text', 'serif'],
        lora: ['Lora', 'serif'],
        source: ['Source Sans Pro', 'sans-serif'],
        ubuntu: ['Ubuntu', 'sans-serif'],
        dancing: ['Dancing Script', 'cursive'],
        pacifico: ['Pacifico', 'cursive'],
        caveat: ['Caveat', 'cursive'],
        bebas: ['Bebas Neue', 'sans-serif'],
        oswald: ['Oswald', 'sans-serif'],
        abril: ['Abril Fatface', 'serif'],
        bungee: ['Bungee', 'sans-serif'],
        righteous: ['Righteous', 'sans-serif'],
        barlow: ['Barlow', 'sans-serif'],
        worksans: ['Work Sans', 'sans-serif'],
        spacegrotesk: ['Space Grotesk', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        dmsans: ['DM Sans', 'sans-serif'],
        plusjakarta: ['Plus Jakarta Sans', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
        figtree: ['Figtree', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
        spacemono: ['Space Mono', 'monospace'],
        jetbrains: ['JetBrains Mono', 'monospace'],
        comfortaa: ['Comfortaa', 'sans-serif'],
        quicksand: ['Quicksand', 'sans-serif'],
        rubik: ['Rubik', 'sans-serif'],
        kalam: ['Kalam', 'cursive'],
        satisfy: ['Satisfy', 'cursive'],
        greatvibes: ['Great Vibes', 'cursive'],
        amatic: ['Amatic SC', 'cursive'],
        shadows: ['Shadows Into Light', 'cursive'],
        permanent: ['Permanent Marker', 'cursive'],
        indie: ['Indie Flower', 'cursive'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [
    function ({ addVariant }) {
      addVariant('light', '.light &')
    },
  ],
}
