import * as LucideIcons from 'lucide-vue-next'
import { h, defineComponent } from 'vue'

function createAnimatedIcon(IconComponent) {
  if (!IconComponent || typeof IconComponent !== 'object') {
    return IconComponent
  }

  return defineComponent({
    name: `Animated${IconComponent.name || 'Icon'}`,
    props: IconComponent.props || {},
    setup(props, { attrs, slots }) {
      return () => h(IconComponent, {
        ...props,
        ...attrs,
        class: ['lucide-animated', attrs.class].filter(Boolean).join(' '),
      }, slots)
    },
  })
}

// Create animated versions of all icons
const wrapIcon = (icon) => {
  if (icon && typeof icon === 'object') {
    return createAnimatedIcon(icon)
  }
  return icon
}

// Export animated versions of icons
export const Loader2 = wrapIcon(LucideIcons.Loader2)
export const Eye = wrapIcon(LucideIcons.Eye)
export const Download = wrapIcon(LucideIcons.Download)
export const AlertCircle = wrapIcon(LucideIcons.AlertCircle)
export const Copy = wrapIcon(LucideIcons.Copy)
export const Check = wrapIcon(LucideIcons.Check)
export const Info = wrapIcon(LucideIcons.Info)
export const X = wrapIcon(LucideIcons.X)
export const Plus = wrapIcon(LucideIcons.Plus)
export const Settings = wrapIcon(LucideIcons.Settings)
export const RefreshCw = wrapIcon(LucideIcons.RefreshCw)
export const FolderPlus = wrapIcon(LucideIcons.FolderPlus)
export const ImagePlus = wrapIcon(LucideIcons.ImagePlus)
export const CheckSquare = wrapIcon(LucideIcons.CheckSquare)
export const Lock = wrapIcon(LucideIcons.Lock)
export const MoreVertical = wrapIcon(LucideIcons.MoreVertical)
export const Star = wrapIcon(LucideIcons.Star)
export const FolderKanban = wrapIcon(LucideIcons.FolderKanban)
export const EyeOff = wrapIcon(LucideIcons.EyeOff)
export const Mail = wrapIcon(LucideIcons.Mail)
export const ChevronDown = wrapIcon(LucideIcons.ChevronDown)
export const Folder = wrapIcon(LucideIcons.Folder)
export const ChevronLeft = wrapIcon(LucideIcons.ChevronLeft)
export const ChevronRight = wrapIcon(LucideIcons.ChevronRight)
export const ChevronUp = wrapIcon(LucideIcons.ChevronUp)
export const Grid3x3 = wrapIcon(LucideIcons.Grid3x3)
export const List = wrapIcon(LucideIcons.List)
export const Image = wrapIcon(LucideIcons.Image)
export const ArrowRight = wrapIcon(LucideIcons.ArrowRight)
export const Play = wrapIcon(LucideIcons.Play)
export const Pause = wrapIcon(LucideIcons.Pause)
export const Heart = wrapIcon(LucideIcons.Heart)
export const Share2 = wrapIcon(LucideIcons.Share2)
export const LockOpen = wrapIcon(LucideIcons.LockOpen)
export const MessageSquare = wrapIcon(LucideIcons.MessageSquare)
export const Sparkles = wrapIcon(LucideIcons.Sparkles)
export const ThumbsUp = wrapIcon(LucideIcons.ThumbsUp)
export const LogOut = wrapIcon(LucideIcons.LogOut)
export const CheckCircle2 = wrapIcon(LucideIcons.CheckCircle2)
export const HardDrive = wrapIcon(LucideIcons.HardDrive)
export const ImageIcon = wrapIcon(LucideIcons.ImageIcon)
export const ChevronsLeft = wrapIcon(LucideIcons.ChevronsLeft)
export const ChevronsRight = wrapIcon(LucideIcons.ChevronsRight)
export const Pencil = wrapIcon(LucideIcons.Pencil)
export const Trash2 = wrapIcon(LucideIcons.Trash2)
export const ArrowUpDown = wrapIcon(LucideIcons.ArrowUpDown)
export const ExternalLink = wrapIcon(LucideIcons.ExternalLink)
export const Type = wrapIcon(LucideIcons.Type)
export const LayoutGrid = wrapIcon(LucideIcons.LayoutGrid)
export const LockKeyhole = wrapIcon(LucideIcons.LockKeyhole)
export const LockKeyholeOpen = wrapIcon(LucideIcons.LockKeyholeOpen)
export const Upload = wrapIcon(LucideIcons.Upload)
export const Activity = wrapIcon(LucideIcons.Activity)
export const ArrowLeft = wrapIcon(LucideIcons.ArrowLeft)
export const BadgeCheck = wrapIcon(LucideIcons.BadgeCheck)
export const BarChart = wrapIcon(LucideIcons.BarChart)
export const Bell = wrapIcon(LucideIcons.Bell)
export const Bold = wrapIcon(LucideIcons.Bold)
export const Box = wrapIcon(LucideIcons.Box)
export const BoxIcon = wrapIcon(LucideIcons.BoxIcon)
export const Calendar = wrapIcon(LucideIcons.Calendar)
export const CalendarIcon = wrapIcon(LucideIcons.CalendarIcon)
export const CheckCircle = wrapIcon(LucideIcons.CheckCircle)
export const Circle = wrapIcon(LucideIcons.Circle)
export const Clock = wrapIcon(LucideIcons.Clock)
export const Cloud = wrapIcon(LucideIcons.Cloud)
export const CreditCard = wrapIcon(LucideIcons.CreditCard)
export const Edit = wrapIcon(LucideIcons.Edit)
export const Facebook = wrapIcon(LucideIcons.Facebook)
export const ArrowDownUp = wrapIcon(LucideIcons.ArrowDownUp)
export const ChevronsUpDown = wrapIcon(LucideIcons.ChevronsUpDown)
export const Gift = wrapIcon(LucideIcons.Gift)
export const Globe = wrapIcon(LucideIcons.Globe)
export const GripVertical = wrapIcon(LucideIcons.GripVertical)
export const History = wrapIcon(LucideIcons.History)
export const Images = wrapIcon(LucideIcons.Images)
export const Instagram = wrapIcon(LucideIcons.Instagram)
export const Italic = wrapIcon(LucideIcons.Italic)
export const Laptop = wrapIcon(LucideIcons.Laptop)
export const LayoutDashboard = wrapIcon(LucideIcons.LayoutDashboard)
export const Link = wrapIcon(LucideIcons.Link)
export const MapPin = wrapIcon(LucideIcons.MapPin)
export const Menu = wrapIcon(LucideIcons.Menu)
export const Mic = wrapIcon(LucideIcons.Mic)
export const Monitor = wrapIcon(LucideIcons.Monitor)
export const Moon = wrapIcon(LucideIcons.Moon)
export const Phone = wrapIcon(LucideIcons.Phone)
export const PieChart = wrapIcon(LucideIcons.PieChart)
export const Rocket = wrapIcon(LucideIcons.Rocket)
export const Search = wrapIcon(LucideIcons.Search)
export const Shield = wrapIcon(LucideIcons.Shield)
export const ShoppingBag = wrapIcon(LucideIcons.ShoppingBag)
export const ShoppingCart = wrapIcon(LucideIcons.ShoppingCart)
export const Slash = wrapIcon(LucideIcons.Slash)
export const Smartphone = wrapIcon(LucideIcons.Smartphone)
export const StickyNote = wrapIcon(LucideIcons.StickyNote)
export const Sun = wrapIcon(LucideIcons.Sun)
export const TrendingUp = wrapIcon(LucideIcons.TrendingUp)
export const Underline = wrapIcon(LucideIcons.Underline)
export const Unlink = wrapIcon(LucideIcons.Unlink)
export const User = wrapIcon(LucideIcons.User)
export const UserIcon = wrapIcon(LucideIcons.UserIcon)
export const Users = wrapIcon(LucideIcons.Users)
export const Video = wrapIcon(LucideIcons.Video)
export const XCircle = wrapIcon(LucideIcons.XCircle)
export const Zap = wrapIcon(LucideIcons.Zap)
export const Database = wrapIcon(LucideIcons.Database)
export const FileEdit = wrapIcon(LucideIcons.FileEdit)
export const FileSpreadsheet = wrapIcon(LucideIcons.FileSpreadsheet)
export const ListTodo = wrapIcon(LucideIcons.ListTodo)
export const MailIcon = wrapIcon(LucideIcons.MailIcon)
export const Presentation = wrapIcon(LucideIcons.Presentation)
export const Users2 = wrapIcon(LucideIcons.Users2)
export const Album = wrapIcon(LucideIcons.Album)
export const FileImage = wrapIcon(LucideIcons.FileImage)
export const FolderOpen = wrapIcon(LucideIcons.FolderOpen)
export const Palette = wrapIcon(LucideIcons.Palette)
export const SparklesIcon = wrapIcon(LucideIcons.SparklesIcon)
export const BookOpen = wrapIcon(LucideIcons.BookOpen)
export const Code = wrapIcon(LucideIcons.Code)
export const HelpCircle = wrapIcon(LucideIcons.HelpCircle)
export const GraduationCap = wrapIcon(LucideIcons.GraduationCap)
export const Lightbulb = wrapIcon(LucideIcons.Lightbulb)
export const ArrowRightToLine = wrapIcon(LucideIcons.ArrowRightToLine)
export const FastForward = wrapIcon(LucideIcons.FastForward)
export const Rewind = wrapIcon(LucideIcons.Rewind)
export const Volume1 = wrapIcon(LucideIcons.Volume1)
export const Volume2 = wrapIcon(LucideIcons.Volume2)
export const VolumeX = wrapIcon(LucideIcons.VolumeX)
export const Maximize = wrapIcon(LucideIcons.Maximize)
export const Minimize = wrapIcon(LucideIcons.Minimize)
export const CheckSquare2 = wrapIcon(LucideIcons.CheckSquare2)
export const ArrowDown = wrapIcon(LucideIcons.ArrowDown)
export const Award = wrapIcon(LucideIcons.Award)
export const Baby = wrapIcon(LucideIcons.Baby)
export const BarChart3 = wrapIcon(LucideIcons.BarChart3)
export const Briefcase = wrapIcon(LucideIcons.Briefcase)
export const Brush = wrapIcon(LucideIcons.Brush)
export const Building = wrapIcon(LucideIcons.Building)
export const Cake = wrapIcon(LucideIcons.Cake)
export const Camera = wrapIcon(LucideIcons.Camera)
export const Car = wrapIcon(LucideIcons.Car)
export const Church = wrapIcon(LucideIcons.Church)
export const Coffee = wrapIcon(LucideIcons.Coffee)
export const Compass = wrapIcon(LucideIcons.Compass)
export const Dumbbell = wrapIcon(LucideIcons.Dumbbell)
export const FileText = wrapIcon(LucideIcons.FileText)
export const FileVideo = wrapIcon(LucideIcons.FileVideo)
export const Film = wrapIcon(LucideIcons.Film)
export const Filter = wrapIcon(LucideIcons.Filter)
export const SlidersHorizontal = wrapIcon(LucideIcons.SlidersHorizontal)
export const Flower2 = wrapIcon(LucideIcons.Flower2)
export const Gamepad2 = wrapIcon(LucideIcons.Gamepad2)
export const Gem = wrapIcon(LucideIcons.Gem)
export const Home = wrapIcon(LucideIcons.Home)
export const Layers = wrapIcon(LucideIcons.Layers)
export const LinkIcon = wrapIcon(LucideIcons.LinkIcon)
export const ListChecks = wrapIcon(LucideIcons.ListChecks)
export const Mountain = wrapIcon(LucideIcons.Mountain)
export const Move = wrapIcon(LucideIcons.Move)
export const Music = wrapIcon(LucideIcons.Music)
export const Paintbrush = wrapIcon(LucideIcons.Paintbrush)
export const PartyPopper = wrapIcon(LucideIcons.PartyPopper)
export const PenTool = wrapIcon(LucideIcons.PenTool)
export const PencilIcon = wrapIcon(LucideIcons.PencilIcon)
export const Plane = wrapIcon(LucideIcons.Plane)
export const Radio = wrapIcon(LucideIcons.Radio)
export const RotateCcw = wrapIcon(LucideIcons.RotateCcw)
export const Ruler = wrapIcon(LucideIcons.Ruler)
export const Scissors = wrapIcon(LucideIcons.Scissors)
export const Ship = wrapIcon(LucideIcons.Ship)
export const Shirt = wrapIcon(LucideIcons.Shirt)
export const Square = wrapIcon(LucideIcons.Square)
export const Target = wrapIcon(LucideIcons.Target)
export const TreePine = wrapIcon(LucideIcons.TreePine)
export const Trophy = wrapIcon(LucideIcons.Trophy)
export const Utensils = wrapIcon(LucideIcons.Utensils)
export const Wand2 = wrapIcon(LucideIcons.Wand2)
export const Watch = wrapIcon(LucideIcons.Watch)
export const Waves = wrapIcon(LucideIcons.Waves)
export const XSquare = wrapIcon(LucideIcons.XSquare)
export const ZoomIn = wrapIcon(LucideIcons.ZoomIn)
export const ZoomOut = wrapIcon(LucideIcons.ZoomOut)

// Export all remaining icons from lucide-vue-next (fallback for any not explicitly listed)
const allIcons = new Proxy({}, {
  get(target, prop) {
    if (prop in LucideIcons) {
      return wrapIcon(LucideIcons[prop])
    }
    return undefined
  },
  has(target, prop) {
    return prop in LucideIcons
  },
  ownKeys() {
    return Object.keys(LucideIcons)
  },
})

// Re-export everything else dynamically via default export
export default allIcons
